### PR TITLE
Add /plugman download

### PR DESCRIPTION
**Pull request by Toshimichi0915**

### CODE REVIEW

**Comment by TheBlackEntity** [comment]
I'm unsure how often this command will come in handy since most plugins are downloaded from spigotmc - Which does not return direct urls to the files.

Did you test this?

**Comment by Toshimichi0915** [comment]
I know there's a plugin that can download Spigot plugins. However, to download Spigot plugins directly we need to rely on third-party API called "Spiget", which I do not trust because they are essentially redistributing plugins without authors' consent.

If someone wants to download Spigot plugins directly, they can manually use Spiget API to get direct download link. So I don't think it was essential to implement that feature.

**Comment by TheBlackEntity** [comment]
I'll think about adding this command.

I personally won't use it though.


I have to wait before I can merge anyway...

I currently don't have a PC so I cannot test this properly.


Thank you very much for your time and effort :)

**Comment by Toshimichi0915** [comment]
Todo: I forgot to update plugin.yml
fix tomorrow

**Comment by Toshimichi0915** [comment]
I added Spiget support. Can you check?

**Comment by TheBlackEntity** [comment]
Weird, I thought the license file and directory was no problem since I had this once on Win10 🤔


Thanks for adding Spigot, the command is now way more useful.


I still don't have a PC rn though...

I'll probably search for someone, who I can trust, to test it for me.


Again, thank you for your contribution :]

**Comment by Toshimichi0915** [comment]
When can you merge?

**Comment by TheBlackEntity** [comment]
> When can you merge?

I'm still missing a PC.

Should be able to merge in the next 5 weeks though

**Pull request merged**
